create table public.guests (
 id bigint generated by default as identity primary key,
 nombre text not null,
 asiste boolean not null,
 acompanantes jsonb not null default '[]'::jsonb,
 codigo text unique not null,
 entrada boolean not null default false,
 entrada_at timestamptz,
 created_at timestamptz not null default now()
);
alter table public.guests enable row level security;
-- El backend usa la service key, que NO debe ponerse en el navegador.
